# Generated by Django 4.0.4 on 2022-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='nameCity',
            new_name='name',
        ),
    ]
